services:
  api:
    build: .
    image: docker.jashom.com/jashom-backend:${TAG:-latest}
    container_name: jashom-backend

    ports:
      - "2131:5000"

    env_file:
      - .env

    restart: unless-stopped
